name: Schedule to send notification to wechat
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  notion_remind:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run  script
        run: |
          python notion_remind.py
        env:
          NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
          NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
          SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }}
